platform :ios, '8.0'
# Uncomment the next line if you're using Swift or would like to use dynamic frameworks
#use_frameworks!

target 'APPSummary' do
    pod 'CYLTabBarController', '~> 1.17.6'
    pod 'lottie-ios', '~> 2.1.4'
    pod 'TYAttributedLabel', '~> 2.6.2'
    pod 'SDWebImage', '~> 4.2.1'
    pod 'JPFPSStatus', '~> 0.1.1'
    pod 'Masonry', '~> 1.1.0'
    pod 'AFNetworking', '~> 3.1.0'
    pod 'GPUImage', '~> 0.1.7'
    pod 'YYCache', '~> 1.0.4'
    #     pod 'FJAlertView', '~> 0.0.4'
    pod 'IQKeyboardManager', '~> 6.0.2'
    #     pod 'FTLinearActivityIndicator', '~> 1.0.4'
    pod 'FDFullscreenPopGesture', '~> 1.1'
    #     pod 'AXWebViewController', '~> 0.7.1'
    pod 'FJAlertView', '~> 0.0.4'
    pod 'MJExtension', '~> 3.0.13'
    pod 'JxbDebugTool', '~> 4.5'
    pod 'YYImage', '~> 1.0.4'
    pod 'MJRefresh', '~> 3.1.15.3'
    pod 'MBProgressHUD', '~> 1.1.0'
    pod 'BarrageRenderer', '~> 2.1.0'
    pod 'MLEmojiLabel', '~> 1.0.2'
#    pod 'AAChartKit', '~> 2.1.6'
    pod 'KVOController', '~> 1.2.0'
#    pod 'YYTNetwork', '~> 0.1.5'
    pod 'pop', '~> 1.0.10'
    pod 'FLEX', '~> 2.4.0'
    pod 'Bugly', '~> 2.5.0'
    pod 'YYText', '~> 1.0.7'
    pod 'Aspects', '~> 1.4.1'
    pod 'RTRootNavigationController', '~> 0.6.7'
    pod 'TZImagePickerController', '~> 2.1.6'
    pod 'NYTPhotoViewer', '~> 1.2.0'
    pod 'SVProgressHUD', '~> 2.1.2'
    pod 'FLAnimatedImage', '~> 1.0.12'
#    pod 'ZFPlayer', '~> 3.0.9.1'
#    pod 'WMPlayer', '~> 5.0.0'
    pod 'YYCategories', '~> 1.0.4'
    #分页
    pod 'WMPageController', '~> 1.4.1'
    #滑动菜单
    pod 'VTMagic'
end
